---
all:
  hosts:
    w2019-test:
      ansible_host: 127.0.0.1
      ansible_user: vagrant
      ansible_password: vagrant
      ansible_connection: winrm
      ansible_winrm_transport: ntlm
      ansible_winrm_server_cert_validation: ignore
      ansible_winrm_scheme: http
      ansible_port: 55985

